In [1]:
# The standard import
import numpy as np

# Array operation

The ususal algebraic operation on matrices are implemented:

1. Addition `+`
2. Subtraction `-`

__Note__: the multiplication `*` is __not__ the usual matrix multiplication, but instead termwise multiplication (the Hadamard product).

If we want to multiply two matrices we use the `@` operator.

In [2]:
# create a matrix
a = np.array([[5,2,1],[0,3,2],[9,-1,-2]])
print(a)

[[ 5  2  1]
 [ 0  3  2]
 [ 9 -1 -2]]


In [3]:
# create a second matrix
b = np.array([[0,1,-1],[1,-2,3],[1,-1,-1]])
print(b)

[[ 0  1 -1]
 [ 1 -2  3]
 [ 1 -1 -1]]


In [4]:
# add them
a + b

array([[ 5,  3,  0],
       [ 1,  1,  5],
       [10, -2, -3]])

In [5]:
# subtract
a - b

array([[ 5,  1,  2],
       [-1,  5, -1],
       [ 8,  0, -1]])

In [6]:
# hadamard product
a * b

array([[ 0,  2, -1],
       [ 0, -6,  6],
       [ 9,  1,  2]])

In [7]:
# matrix multiplication
a @ b

array([[  3,   0,   0],
       [  5,  -8,   7],
       [ -3,  13, -10]])

### Conditions

We can find all the positions whose entries satisfy some condition, as well as the entries in question.


In [8]:
# create an array
print(a)

[[ 5  2  1]
 [ 0  3  2]
 [ 9 -1 -2]]


To find the location of, e.g., the entries greater than or equal to 3, we can just do `a >= 3`.

In [9]:
a >= 3

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False]])

In [10]:
# the locations of the  elements divisible by 3
a % 3 == 0

array([[False, False, False],
       [ True,  True, False],
       [ True, False, False]])

We can then use this to access the elements in question. Note that we get a 1D-array back.

In [11]:
a[a % 3 == 0]

array([0, 3, 9])

In [12]:
# general indexing
a[2,1]

-1

### Creating new arrays from existing arrays

Two ways are

1. Slicing
2. Combining arrays

#### Slicing

We can use the standard slicing operator for numpy arrays.

In [13]:
# slice the array a

# the 2x2 in the  bottom right corner
a[1:3,1:3]

array([[ 3,  2],
       [-1, -2]])

### Combining

1. `np.vstack()` stack matrices vertically
2. `np.hstack()` stack matrices horizontally


#### Vertical stack

Let
$$
A = \begin{pmatrix}
5  & 2  &  1 \\
0  & 3  &  2 \\
9 & -1  & -2
\end{pmatrix}
\quad
B =
\begin{pmatrix}
0 &  1 & -1 \\
1 & -2 &  3 \\
1 & -1 & -1
\end{pmatrix}
$$
Then, by vertically stacking them, we mean the matrix
$$
\begin{pmatrix}
A \\
B
\end{pmatrix} =
\begin{pmatrix}
5  & 2  &  1 \\
0  & 3  &  2 \\
9 & -1  & -2 \\
0 &  1 & -1 \\
1 & -2 &  3 \\
1 & -1 & -1
\end{pmatrix}
$$

In [14]:
print(a,'\n\n',b)

[[ 5  2  1]
 [ 0  3  2]
 [ 9 -1 -2]] 

 [[ 0  1 -1]
 [ 1 -2  3]
 [ 1 -1 -1]]


In [15]:
# stack vertically
np.vstack((a,b))

array([[ 5,  2,  1],
       [ 0,  3,  2],
       [ 9, -1, -2],
       [ 0,  1, -1],
       [ 1, -2,  3],
       [ 1, -1, -1]])

#### Horizontal stacking

With the same $A$ and $B$, their horizontal stacking is
$$
\begin{pmatrix}
A B
\end{pmatrix} 
=
\begin{pmatrix}
5 &   2 &  1 &  0 &  1 & -1 &  5 &  2 &  1 \\
0 &  3 &  2 &  1 & -2 &  3 &  0 &  3 &  2 \\
9 & -1 & -2 &  1 & -1 & -1 &  9 & -1 & -2
\end{pmatrix}
$$

In [16]:
# and horizontally
np.hstack((a,b,a))

array([[ 5,  2,  1,  0,  1, -1,  5,  2,  1],
       [ 0,  3,  2,  1, -2,  3,  0,  3,  2],
       [ 9, -1, -2,  1, -1, -1,  9, -1, -2]])

## Deep and shallow copies

By default, numpy makes "shallow" copies, which means that you have to be careful when you mutate elements.

The `.copy()` method on the other hand creates a completely new array.

In [17]:
print(a)

[[ 5  2  1]
 [ 0  3  2]
 [ 9 -1 -2]]


In [18]:
# use the slice example
c = np.array([[0,1],[1,0]])
c

array([[0, 1],
       [1, 0]])

In [19]:
d = a[1:3,1:3]
d
#a[1:3,1:3]

array([[ 3,  2],
       [-1, -2]])

In [20]:
a[1:3,1:3] = c

In [21]:
a

array([[5, 2, 1],
       [0, 0, 1],
       [9, 1, 0]])

## Transposing and reshaping arrays

Two useful methods for reshaping an array are `.reshape()` and `.transpose()`. Often we have the right entries in an array, but it might have the wrong shape. That's where these two methods come in.

In [22]:
# transpose is just the  ordinary transpose from mathematics.
a.transpose()

# reshape is more versatile.
l = list(range(16))
np.reshape(np.array(l), (2,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

## Example

Let us see how we can take a matrix and make sure all the entries are between $0.0$ and $1.0$, by changing negative entries to $0.0$ and entries larger than $1.0$ to $1.0$.


### Using `np.where()`

The function `np.where()` takes two matrices `x` and `y`, and a condition and depending on the condition, for each position either takes the entry from `x` or `y`.


### using `np.clip()`

## Example

Let us compute the determinant of a tridiagonal $n\times n$-matrix with $5$ on the diagonal and $1$ on the superdiagonal and the subdiagonal.

The function `np.diag()` creates a matrix of zeroes, but with one nonzero diagonal (which does not have to be the main diagonal). A list of the nonzero entries has to be supplied, and optionally which diagonal (if it is not the main diagonal); positive numbers indicate above the main diagonal and negative numbers indicate below the main diagonal.

In [23]:
# Create a function my_tridiag(n) that returns this matrix as a numpy array.
def mytridiag(n):
    # n is an integer giving the size of the matrix
    return np.diag(n*[5]) + np.diag((n-1)*[2],1) + np.diag((n-1)*[2],-1)
    
mytridiag(10)


array([[5, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 5, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 5, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 5, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 5, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 5, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 5, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 5, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 5, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 5]])

## Linalg

There are some useful linear routines for linear algebra in numpy. Note though that we have to prepend the name by `np.linalg` (not just `np`).

1. `np.linalg.inv(A)` for inverting the matrix $A$.
2. `np.linalg.solve(A,b)` for solving the linear system $Ax = b$.
3. `np.linalg.eig(A)` computes the eigenvalues and associated eigenvectors of $A$. 